global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ai-artistic-style-service"
    static_configs:
      - targets: ["localhost:5001"] # Replace with your AI service host and port

